# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: noahjutz/quartz
          path: quartz
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v3
        with:
          repository: noahjutz/oth-2023-wise
          path: oth-2023-wise
          token: ${{ secrets.PAT }}

      - name: Copy files to quartz
        run: |
          ls
          pwd

          rm -rf quartz/content/*
          cp -r oth-2023-wise/vault/* quartz/content
          touch quartz/content/index.md
          echo "Hello, World!" > quartz/content/index.md

          git config --global user.name 'Noah Jutz'
          git config --global user.email 'noahjutz@users.noreply.github.com'

          cd quartz
          git remote set-url --push origin https://noahjutz:$GITHUB_TOKEN@github.com/noahjutz/quartz
          git add .
          git commit -m "Auto Commit"
          git push
